### ISSUE TITLE
Investigate URI problem in bibl records

### ISSUE THREAD

**Issue by nathangibson** [usaybia/zotero2bibl#2]
@wsalesky Can you check what's going on with the conversion? usaybia.net URIs are truncated in both the header and body, as, e.g. https://github.com/usaybia/usaybia-data/blob/master/data/bibl/tei/223VREUY.xml#L56 and https://github.com/usaybia/usaybia-data/blob/master/data/bibl/tei/223VREUY.xml#L82

Did I misconfigure https://github.com/usaybia/zotero2bibl/blob/master/zotero-config.xml ?

**Comment by wsalesky** [comment]
Fixed
